export const environment = {
  production: false,
  tokenKey: 'jwt',
  authPersistKey: 'auth',
  defaultTokenStorage: 'local',
  apiUrl: 'http://localhost:3000/api',
  serverUrl: 'http://localhost:3000',
  requestTimeout: 5000,
  defaultLanguage: 'vi',
  languageLocalStorageKey: 'lang',
  availabelLanguages: ['vi', 'en'],
  manage: ['superadmin', 'admin'],
  firebaseConfig: {
    apiKey: 'API_KEY',
    authDomain: 'AUTH_DOMAIN',
    projectId: 'PROJECT_ID',
    storageBucket: 'STORAGE_BUCKET',
    messagingSenderId: 'MESSAGE_SENDER_ID',
    appId: 'APP_ID',
  },
};
