export const environment = {
  production: true,
  appName: 'Api Documentation',
  appKey: 'secret',
  appPrefix: 'api',
  appVersion: '1.0',
  appUrl: 'http://localhost:3000',
  jwtTtl: 86400,
  dbLog: false,
  migrationsRun: false,
  dbConnection: 'mysql',
  dbHost: 'localhost',
  dbPort: 3306,
  dbName: 'db_name',
  dbUser: 'root',
  dbPass: '',
  pdfUploadPath: 'assets/uploads',
  enableLoginFailedCheck: true,
  maxLoginFailed: 5,
  firebaseServiceAccount: {},
};
